baseURL = 'https://shirishpokhrel.me/'
languageCode = 'en-us'
title = 'Shirish Pokhrel'
theme = 'archie'
publishdir = './public/singurty.github.io/'

[params]
mode="auto"
useCDN=false

[[menu.main]]
name = "home"
url = '/'
weight = 1

[[menu.main]]
name = "blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "rss"
url = "index.xml"
weight = 4
