baseURL = 'https://shirishpokhrel.me/'
languageCode = 'en-us'
title = 'Shirish Pokhrel'
theme = 'archie'
publishdir = './public/singurty.github.io/'

[params]
mode="toggle"
useCDN=false

[[menu.main]]
name = "home"
url = '/'
weight = 1

[[menu.main]]
name = "blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "rss"
url = "/index.xml"
weight = 4

# Code Highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
