baseURL = 'http://shirishpokhrel.me/'
languageCode = 'en-us'
title = 'Shirish Pokhrel'
theme = 'archie'
publishdir = './public/singurty.github.io/'

[params]
mode="auto"
useCDN=false

[[menu.main]]
name = "home"
url = '/'
weight = 1

[[menu.main]]
name = "blog"
url = "/blog"
weight = 2
