baseURL = 'http://shirishpokhrel.me/blog/'
languageCode = 'en-us'
title = 'Blog'
theme = 'archie'
publishdir = '../public/singurty.github.io/blog/'

[params]
mode="auto"
useCDN=false

[[menu.main]]
name = "home"
url = 'http://shirishpokhrel.me/'
weight = 1

[[menu.main]]
name = "blog"
url = "/"
weight = 2
